In [3]:
pip install pandasql


  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26768 sha256=11cedf5ec4cdf00bd471aaecee152090db3e7d758753e36b1b650f0bdf568fe4
  Stored in directory: c:\users\kpnar\appdata\local\pip\cache\wheels\63\e8\ec\75b1df467ecf57b6ececb32cb16f4e86697cbfe55cb0c51f07
Successfully built pandasql


In [4]:
pip install xlrd

Note: you may need to restart the kernel to use updated packages.


In [8]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime, date
from pandasql import sqldf
import pandasql as ps
import seaborn 
mysql = lambda q: sqldf(q, globals())
import re

In [63]:
#Reading the dataset
xls=pd.ExcelFile("HospitalDatabase.xlsx")

#Reading the patients Sheet

df_PA=pd.read_excel(xls,'Patients')

# Reading the EDVisit Sheet

df_EDV=pd.read_excel(xls,'EDVisits')

# Reading the AmbulatoryVisits sheet
 df_AV = pd.read_excel(xls,'AmbulatoryVisits')

    
#Reading the ReAdmissionRegistry 
 df_RE=pd.read_excel(xls,'ReAdmissionRegistry')

#Reading the Discharges sheet
  df_D=pd.read_excel(xls,'Discharges')

#Reading the Providers sheet
df_P=pd.read_excel(xls,'Providers')

#Reading the EDUnique sheet
df_E=pd.read_excel(xls,' EDUnique')

    
    
    


IndentationError: unexpected indent (1581504745.py, line 13)

# 61.np.arange(1,31).reshape(6,5) Find the array slicing to get the elements with values 11,12,16,17.

In [86]:
A = np.arange(1,31)
B = A.reshape(6, 5)
print(B)
B[2:4,0:2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[11, 12],
       [16, 17]])

# 80.Display the data for all 'White Female' patients above the age of 50.   

In [17]:
#xls=pd.ExcelFile("HospitalDatabase.xlsx")
#df_PA=pd.read_excel(xls,'Patients')

df_PA[(df_PA.Race == 'White') 
      & (df_PA.Gender == 'Female') 
      & (df_PA.DateOfBirth.dt.year < (datetime.today().year-50))]

PatientID  FirstName   LastName             DateOfBirth  Gender   Race  \
25          26      Sally       Bing 1972-08-03 00:05:39.560  Female  White   
28          29        Ted      Scott 1967-12-09 05:01:37.892  Female  White   
30          31      Harry       Ding 1960-10-08 01:42:51.212  Female  White   
33          34        Ted        Hue 1960-11-28 18:05:11.459  Female  White   
34          35       Fred        Tye 1966-04-14 06:01:07.169  Female  White   
..         ...        ...        ...                     ...     ...    ...   
865        866   Jermayne    Lowndes 1970-12-09 04:49:48.933  Female  White   
866        867       Gail        Inc 1967-03-10 08:18:47.908  Female  White   
867        868        Des  Heindrick 1969-08-15 11:05:30.165  Female  White   
869        870      Hauck    Rubbens 1963-11-16 03:31:38.929  Female  White   
873        874  Schroeder   McGarvey 1971-12-09 11:56:22.068  Female  White   

    Language  
25   Spanish  
28   Spanish  
30   Spanish  
33   Spanish  
34   Spanish  
..       ...  
865  English  
866  English  
867  English  
869  English  
873  English  

[122 rows x 7 columns]

# #63.List male patients over the age of 60 who have undergone surgery from January-March 2019.


In [62]:
Pva = pd.merge(df_AV, df_P, on = "ProviderID")
avpa = pd.merge(df_PA, Pva, left_on="PatientID", right_on="PatientMRN")
avpa[(avpa.Gender == 'Male')
    & (avpa.DateOfBirth.dt.year < (datetime.today().year-60))
    & (avpa.ProviderSpecialty == 'Surgery')
    & (avpa.DateScheduled.dt.year == 2019)
    & (avpa.DateScheduled.dt.month >= 1)
    & (avpa.DateScheduled.dt.month <= 3)]

NameError: name 'df_AV' is not defined

## 75.Using numpy functions, multiply the following arrays                     a=np.arange(6).reshape(2,3)                                                                            b=np.arange(6).reshape(3,2)

In [29]:

a=np.arange(6).reshape(2,3)
b=np.arange(6).reshape(3,2)
outarr=np.dot(a,b)
print("result",outarr)

result [[10 13]
 [28 40]]


  # #71.Find the count of White Spanish Male.

In [87]:
len (df_PA[(df_PA['Race']=='White') & (df_PA['Language']=='Spanish') & (df_PA['Gender']=='Male')])


15